"""
Library for the Rainbow Grades integration tests.
"""

from collections import defaultdict
from functools import wraps
import multiprocessing
from multiprocessing import cpu_count
import difflib
import inspect
import os
import re
import shutil
import subprocess
import sys
import traceback


INTEGRATION_TEST_ROOT = os.path.dirname(os.path.realpath(__file__))
RAINBOW_GRADES_DIR = os.path.dirname(INTEGRATION_TEST_ROOT)

# Set by run.py when invoked with --update
UPDATE_VALIDATION = False

###################################################################################
# Test registry
#
# Concurrency note (same constraint as Submitty's framework): to survive being
# passed across a process boundary there must be no lambdas in TestcaseFile and
# every wrapper must be annotated with functools.wraps, so that Python can
# pickle them for the worker process.
###################################################################################

class TestcaseFile:
    def __init__(self):
        self.wrapper = type(None)
        self.prebuild = type(None)
        self.testcases = []
        self.testcases_names = []


to_run = defaultdict(lambda: TestcaseFile(), {})


###################################################################################
# Helpers for color
###################################################################################
class ASCIIEscapeManager:
    def __init__(self, codes):
        self.codes = list(map(str, codes))

    def __enter__(self):
        sys.stdout.write(f"\u001B[{';'.join(self.codes)}m")

    def __exit__(self, exc_type, exc_value, traceback):
        sys.stdout.write("\033[0m")

    def __add__(self, other):
        return ASCIIEscapeManager(self.codes + other.codes)


bold = ASCIIEscapeManager([1])
red = ASCIIEscapeManager([31])
green = ASCIIEscapeManager([32])
yellow = ASCIIEscapeManager([33])


###################################################################################
# Output normalization
#
# RainbowGrades output is deterministic apart from two things, both of which are
# properties of *when and where* it ran rather than of the grade computation.
###################################################################################

# The page footer embeds the current year, the most recent git tag, and the
# commit hash.
COPYRIGHT_LINE = re.compile(r"^<p>&copy;.*RainbowGrades.*</p>$")
COPYRIGHT_PLACEHOLDER = "<p>&copy; [YEAR] [RAINBOW GRADES VERSION]</p>"

# Rainbow Grades archives the all students report under a dated filename. The
# contents are compared, so we strip the date out of the name
DATED_OUTPUT = re.compile(r"^output_\d+_\d+_\d+\.(html|csv)$")


def normalize_filename(name):
    dated = DATED_OUTPUT.match(name)
    return f"output_DATE.{dated.group(1)}" if dated else name


def normalize_contents(text):
    return "\n".join(
        COPYRIGHT_PLACEHOLDER if COPYRIGHT_LINE.match(line) else line
        for line in text.split("\n")
    )


class TestcaseWrapper:
    """Passed to every @prebuild and @testcase function as test"""
    # Where Rainbow Grades writes its output
    OUTPUT_DIRECTORIES = (
        "individual_summary_html",
        "all_students_summary_html",
        "all_students_summary_csv",
    )

    MAKEFILE_TEMPLATE = """\
# Generated by integrationTests/lib.py -- do not edit.
USERNAME=integration_test
RAINBOW_GRADES_DIRECTORY={rg_dir}
HWSERVER=localhost
# Never used: the test stages raw_data/ directly instead of rsync'ing it.
REPORTS_DIRECTORY={data_path}/unused_reports

include ${{RAINBOW_GRADES_DIRECTORY}}/MakefileHelper
"""

    def __init__(self, path):
        self.testcase_path = path
        self.data_path = os.path.join(path, "data")
        self.validation_path = os.path.join(path, "validation")
        self.sort_order = "overall"
        self._has_run = False


    def stage_inputs(self):
        """Copy this module's inputs into a clean data/ directory"""
        if os.path.isdir(self.data_path):
            shutil.rmtree(self.data_path)
        os.makedirs(self.data_path)

        shutil.copy(
            os.path.join(self.testcase_path, "customization.json"),
            os.path.join(self.data_path, "customization.json"),
        )
        shutil.copytree(
            os.path.join(self.testcase_path, "raw_data"),
            os.path.join(self.data_path, "raw_data"),
        )

        with open(os.path.join(self.data_path, "Makefile"), "w") as make_file:
            make_file.write(self.MAKEFILE_TEMPLATE.format(
                rg_dir=RAINBOW_GRADES_DIR,
                data_path=self.data_path,
            ))


    def build(self):
        """Fetch dependencies and compile Rainbow Grades through the normal Makefilehelper path"""
        self._make("nlohmann_json", "fetch_dependencies")
        self._make("compile", "build")

    def run_rainbow_grades(self, sort_order=None):
        """Run Rainbow Grades and normalize its output into data/normalized"""
        self._make(sort_order or self.sort_order, "run")
        self._normalize_outputs()
        self._has_run = True

    def ensure_run(self):
        """Run Rainbow Grades once per module, on demand
        Test cases can be run individually on the command line, so a
        testcase cannot assume that an earlier one already produced output.
        """
        if not self._has_run:
            self.run_rainbow_grades()

    def _make(self, target, log_name):
        log_path = os.path.join(self.data_path, f"{log_name}_output.txt")
        with open(log_path, "w") as log_file:
            return_code = subprocess.call(
                ["make", target],
                cwd=self.data_path,
                stdout=log_file,
                stderr=subprocess.STDOUT,
            )
        if return_code != 0:
            self.debug_print(f"{log_name}_output.txt")
            raise RuntimeError(
                f"make {target} exited with code {return_code}"
            )

    def _normalize_outputs(self):
        """Write a normalized copy of every file to data/normalized"""
        normalized_root = os.path.join(self.data_path, "normalized")
        if os.path.isdir(normalized_root):
            shutil.rmtree(normalized_root)
        os.makedirs(normalized_root)

        for name in ("output.html", "output.csv"):
            source = os.path.join(self.data_path, name)
            if os.path.isfile(source):
                with open(source) as src, open(os.path.join(normalized_root, name), "w") as out:
                    out.write(normalize_contents(src.read()))

        for directory in self.OUTPUT_DIRECTORIES:
            source_dir = os.path.join(self.data_path, directory)
            if not os.path.isdir(source_dir):
                continue
            target_dir = os.path.join(normalized_root, directory)
            os.makedirs(target_dir, exist_ok=True)
            for name in sorted(os.listdir(source_dir)):
                source = os.path.join(source_dir, name)
                if not os.path.isfile(source):
                    continue
                # Per-student JSON holds exam seating assignments, which are
                # null unless seating is configured. Nothing to compare.
                if name.endswith(".json"):
                    continue
                target = os.path.join(target_dir, normalize_filename(name))
                with open(source) as src, open(target, "w") as out:
                    out.write(normalize_contents(src.read()))

    def diff(self, f1, f2=""):
        """Compare a normalized output to the expected output
        f1 is relative to data/normalized and f2 is relative to validation
        """
        if not f2:
            f2 = f1

        self.ensure_run()
        filename1 = os.path.join(self.data_path, "normalized", f1)
        filename2 = os.path.join(self.validation_path, f2)

        if UPDATE_VALIDATION:
            os.makedirs(os.path.dirname(filename2), exist_ok=True)
            shutil.copy(filename1, filename2)
            return

        if not os.path.isfile(filename1):
            raise RuntimeError(f"Rainbow Grades did not produce {f1}")
        if not os.path.isfile(filename2):
            raise RuntimeError(
                f"No golden file {f2}. Run ./run.py --update"
            )

        with open(filename1) as file1, open(filename2) as file2:
            actual = file1.readlines()
            expected = file2.readlines()

        if actual == expected:
            return

        diff = "".join(list(difflib.unified_diff(
            expected, actual,
            fromfile=f"validation/{f2}",
            tofile=f"data/normalized/{f1}",
            n=1,
        ))[:80])
        raise RuntimeError(f"Difference in {f1}\n\n{diff}")

    def diff_directory(self, directory):
        """Diff every golden file in `directory`, flag any extras"""
        self.ensure_run()
        actual_dir = os.path.join(self.data_path, "normalized", directory)
        golden_dir = os.path.join(self.validation_path, directory)

        actual = set(os.listdir(actual_dir)) if os.path.isdir(actual_dir) else set()

        if UPDATE_VALIDATION:
            if os.path.isdir(golden_dir):
                shutil.rmtree(golden_dir)
            for name in sorted(actual):
                self.diff(os.path.join(directory, name))
            return

        golden = set(os.listdir(golden_dir)) if os.path.isdir(golden_dir) else set()

        missing = sorted(golden - actual)
        unexpected = sorted(actual - golden)
        if missing or unexpected:
            problems = "".join(
                [f"\n missing: {directory}/{n}" for n in missing]
                + [f"\n unexpected: {directory}/{n}" for n in unexpected]
            )
            raise RuntimeError(f"Output file set changed in {directory}:{problems}")

        for name in sorted(golden):
            self.diff(os.path.join(directory, name))

    def get_grades(self):
        """Parse output.csv into {username: {column: value}}
        Allow a testcase to assert on a specific number instead of the whole file,
        failures can be more specific and verbose about what went wrong.
        """
        import csv

        self.ensure_run()
        path = os.path.join(self.data_path, "normalized", "output.csv")
        with open(path, newline="") as csv_file:
            rows = list(csv.reader(csv_file))

        header = [column.strip() for column in rows[0]]
        grades = {}
        for row in rows[1:]:
            if not row or not row[0].strip():
                continue
            grades[row[0].strip()] = {
                header[i]: row[i].strip()
                for i in range(min(len(header), len(row)))
            }
        return grades

    def debug_print(self, f):
        """Print a file from the run directory, helpful for CI failures"""
        filename = os.path.join(self.data_path, f)
        print("\nDEBUG PRINT: ", filename)
        if os.path.exists(filename):
            with open(filename) as fin:
                print(fin.read())
        else:
            print(" < file does not exist >")


###################################################################################
# Runner
###################################################################################

def run_tests(names):
    arguments = []      # Arguments for __run_single_test_module(list<str>, TestcaseFile)
    for name in sorted(names):
        name = name.split(".")
        if name[0] not in to_run:
            available = ", ".join(sorted(to_run.keys()))
            raise SystemExit(
                f"Unknown test module '{name[0]}'. Available modules: {available}"
            )
        case = to_run[name[0]]
        if len(name) > 1 and name[1].lower() not in [
            n.lower() for n in case.testcases_names]:
            available = ", ".join(case.testcases_names)
            raise SystemExit(
                f"Unknown testcase '{name[1]}' in module '{name[0]}'. "
                f"Available testcases: {available}"
            )
        arguments.append((name, case))

    # NOTE: modules run in parallel, testcases with in a module run sequentially
    # on one worker so they can share the compiled binary and directories.

    if len(arguments) == 1:
        results = [__run_single_test_module(*arguments[0])]
    else:
        # Each test module is loaded by tests/__init__.py under a bare name
        # (e.g. "extra_credit") that only exists in sys.modules, not as a
        # real importable package. A worker needs that already done before
        # it can unpickle tasks referencing those modules' functions, which
        # only "spawn" (the macOS/Windows default) leaves out, since it
        # starts from a blank interpreter instead of copying the parent's
        # already-populated sys.modules. Forcing "fork" keeps the loaded
        # modules.
        with multiprocessing.get_context("fork").Pool(min(cpu_count(), len(arguments))) as p:
            results = p.starmap(__run_single_test_module, arguments)

    if False in results: 
        with bold + red:
            print(f"{results.count(True)}/{len(results)} modules passed")
        sys.exit(1)
    else:
        with bold + green:
            print(f"All {len(results)} modules passed")


def run_all():
    run_tests(to_run.keys())


def __run_single_test_module(name, case):
    key = name[0]
    with bold:
        print(f"---- BEGIN TEST MODULE {key.upper()} ----")

    module_success = __compile_test_module(case)
    if module_success:
        testcases = __collect_test_cases(case, name)
        succeed_count = len(testcases)
        for index, f in zip(range(1, len(testcases) + 1), testcases):
            if not __execute_test_case(index, f):
                succeed_count -= 1
        if succeed_count == len(testcases):
            with bold + green: 
                print("All testcases passed")
        else:
            with bold + red:
                print(f"{succeed_count}/{len(testcases)} testcases passed")
            module_success = False

    if not module_success and isinstance(case.wrapper, TestcaseWrapper):
        with yellow:
            print(f"Scratch directory kept at {case.wrapper.data_path}")

    with bold:
        print(f"---- END TEST MODULE {key.upper()} ----")
    print()
    return module_success

def __compile_test_module(case):
    try:
        print("Starting compilation...")
        case.prebuild()
        case.wrapper.build()
        print("Finished comilation...")
        return True
    except Exception as e:
        print(f"Build failed with exception: {e}")
        return False


def __collect_test_cases(case, name):
    if len(name) > 1:
        return [
            case.testcases_names[i]
            for i in range(len(case.testcases))
            if str(case.testcase_names[i]).lower() == name[1].lower()
        ]
    return case.testcases


def __execute_test_case(index, test_case):
    try:
        test_case()
        return True
    except Exception as e:
        with bold + red:
            lineno = None
            tb = traceback.extract_tb(sys.exc_info()[2])
            for i in range(len(tb) - 1, -1, -1):
                if os.path.basename(tb[i][0]) == "__init__.py":
                    lineno = tb[i][1]
            print(f"Testcase {index} failed on line {lineno} with exception: {e}")
        return False


###################################################################################
# Decorators
###################################################################################

def prebuild(func):
    """Register a function that stages inputs before the module is compiled"""
    mod = inspect.getmodule(inspect.stack()[1][0])
    path = os.path.dirname(mod.__file__)
    modname = mod.__name__
    tw = TestcaseWrapper(path)

    @wraps(func) # Allows pickling for this lambda
    def wrapper():
        print(f"Starting prebuild for {modname}...", end="")
        func(tw)
        print("Done")

    global to_run
    to_run[modname].wrapper = tw
    to_run[modname].prebuild = wrapper
    return wrapper

# inspect.stack() index 1 is the frame of the module calling this decorator,
# which gives us the module's path and name without the test author repeating
# them.
def testcase(func):
    """Register a single check within a test module"""
    mod = inspect.getmodule(inspect.stack()[1][0])
    path = os.path.dirname(mod.__file__)
    modname = mod.__name__
    tw = TestcaseWrapper(path)

    @wraps(func) # allows pickling for this lambda
    def wrapper():
        print(f"Starting testcase {modname}.{func.__name__}...", end="")
        try:
            func(tw)
            with bold + green:
                print("PASSED")
        except Exception:
            with bold + red:
                print("FAILED")
            # blank raise will raise the last exception as is
            raise

    global to_run
    to_run[modname].wrapper = tw
    to_run[modname].testcases.append(wrapper)
    to_run[modname].testcases_names.append(func.__name__)
    return wrapper
