"""
Library for the Rainbow Grades integration tests.
"""

from collections import defaultdict
from functools import wraps
from multiprocessing import Pool, cpu_count
import difflib
import inspect
import os
import re
import shutil
import subprocess
import sys
import traceback


INTEGRATION_TEST_ROOT = os.path.dirname(os.path.realpath(__file__))
RAINBOW_GRADES_DIR = os.path.dirname(INTEGRATION_TEST_ROOT)

# Set by run.py when invoked with --update
UPDATE_VALIDATION = False

###################################################################################
# Test registry
#
# Concurrency note (found in Submitty's framework): to survive being
# passed across a process boundary there must be no lambdas in TestcaseFile and
# every wrapper must be annotated with functools.wraps, so that Python can
# pickle them for the worker process.
###################################################################################

class TestcaseFile:
    def __init__(self):
        self.wrapper = type(None)
        self.prebuild = type(None)
        self.testcases = []
        self.testcases_names = []


to_run = defaultdict(lambda: TestcaseFile(), {})


###################################################################################
# Helpers for color
###################################################################################
class ASCIIEscapeManager:
    def __init__(self, codes):
        self.codes = list(map(str, codes))

    def __enter__(self):
        sys.stdout.write(f"\u001B[{';'.join(self.codes)}m")

    def __exit__(self, exc_type, exc_value, traceback):
        sys.stdout.write("\033[0m")

    def __add__(self, other):
        return ASCIIEscapeManager(self.codes + other.codes)


bold = ASCIIEscapeManager([1])
red = ASCIIEscapeManager([31])
green = ASCIIEscapeManager([32])
yellow = ASCIIEscapeManager([33])


###################################################################################
# Output normalization
#
# RainbowGrades output is deterministic apart from two things, both of which are
# properties of *when and where* it ran rather than of the grade computation.
###################################################################################

# The page footer embeds the current year, the most recent git tag, and the
# commit hash.
COPYRIGHT_LINE = re.compile(r"^<p>copy;.*RainbowGrades.*</p>$")
COPYRIGHT_PLACEHOLDER = "<p>&copy; [YEAR] [RAINBOW GRADES VERESION]</p>"

# Rainbow Grades archives the all students report under a dated filename. The
# contents are compared, so we strip the date out of the name
DATED_OUTPUT = re.compile(r"output_\d+_\d+_\d+_\d+\.(html|csv)$")


def normalize_filename(name):
    dated = DATED_OUTPUT.match(name)
    return f"output_DATE.{dated.group(1)}" if dated else name


def normalize_contents(text):
    return "\n".join(
        COPYRIGHT_PLACEHOLDER if COPYRIGHT_LINE.match(line) else line
        for line in text.split("\n")
    )


class TestcaseWrapper:
    """Passed to every @prebuild and @testcase function as test"""
    # Where Rainbow Grades writes its output
    OUTPUT_DIRECTORIES = (
        "individual_summary_html",
        "all_students_summary_html",
        "all_students_summary_csv",
    )

    MAKEFILE_TEMPLATE = """\
        # Generated by integrationTests/lib.py -- do not edit.
        USERNAME=integration_test
        RAINBOW_GRADES_DIRECTORY={rg_dir}
        HWSERVER=localhost
        # Never used: the test stages raw_data/ directly instead of rsync'ing it.
        REPORTS_DIRECTORY={data_path}/unused_reports

        include ${{RAINBOW_GRADES_DIRECTORY}}/MakefileHelper
    """

    def __init__(self, path):
        self.testcase_path = path
        self.data_path = os.path.join(path, "data")
        self.validation_path = os.path.join(path, "validation")
        self.sort_order = "overall"
        self._has_run = False


    def stage_inputs(self):
        """Copy this module's inputs into a clean data/ directory"""
        if os.path.isdir(self.data_path):
            shutil.rmtree(self.data_path)
        os.makedirs(self.data_path)

        shutil.copy(
            os.path.join(self.testcase_path, "customization.json"),
            os.path.join(self.data_path, "customization.json"),
        )
        shutil.copytree(
            os.path.join(self.testcase_path, "raw_data"),
            os.path.join(self.data_path, "raw_data"),
        )

        with open(os.path.join(self.data_path, "Makefile"), "w") as make_file:
            make_file.write(self.MAKEFILE_TEMPLATE.format(
                rg_dir=RAINBOW_GRADES_DIR,
                data_path=self.data_path,
            ))


    def build(self):
        """Compile Rainbow Grades through the normal Makefilehelper path"""
        self._make("compile", "build")

    def run_rainbow_grades(self, sort_order=None):
        """Run Rainbow Grades and normalize its output"""
        self._make(sort_order or self.sort_order, "run")
        self._normalize_outputs()
        self._has_run = True

    def ensure_run(self):
        """Run Rainbow Grades once per module"""
        if not self._has_run
            self.run_rainbow_grades()

    def _make(self, target, log_name):
        log_path = os.path.join(self.data_path, f"{log_name}_output.txt")
        with open(log_path, "w") as log_file:
            return_code = subprocess.call(
                ["make", target],
                cwd=self.data_path,
                stdout=log_file,
                stderr=subprocess.STDOUT,
            )
        if return_code != 0:
            self.debug_print(f"{log_name}_output.txt")
            raise RuntimeError(
                f"make {target} exited with code {return_code}"
            )
        