name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-tests:
    name: RainbowGrades Integration Tests
    runs-on: ubuntu-22.04
    container: submitty/rainbow-grades-tests:latest
    steps:
      - uses: actions/checkout@v7

      - name: Run integration tests
        working-directory: integrationTests
        run: ./run.py

      - name: Upload output on failure
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: rainbow-grades-test-output
          path: integrationTests/tests/*/data/
          retention-days: 3
